### ISSUE TITLE
기념품 추천

### ISSUE THREAD

**Issue by jongfeel** [ThinkAboutSoftware/HomeComingDay2020#1]
에세이 책? 팽대원님 의견

**Comment by fora22** [comment]
고급 타월로 변경됐네요 ㅋㅋㅋㅋ

**Comment by jongfeel** [comment]
아하 사실은...

대원님 이전에 의견을 주신 분이 있어서 적은 거고요.

많은 분들의 의견이 타월이 싫고 책이 좋다고 하면 그렇게 바뀔 수도 있습니다.

그런데 제 느낌상 활발하게 의견 교환이 일어날 것 같지 않기 때문에 그냥 타월이 될 거 같아요.

---

타월 의견 주신 분 역시 이번 home coming day에 참석하는 분이고
대원님 보다 더 먼저 의견을 주셨던 분입니다!

**Comment by yoonucho** [comment]
어라? 그러면 저는 책이 더 좋습니다!  📖

**Comment by jongfeel** [comment]
책이 좋다고 하시면 각자 취향을 조사한 후에 주문을 해야 겠네요.

투표 같은걸 진행해야 할 것 같습니다.

**Comment by hi-hyein** [comment]
저두 책이 좋아요^_^

**Comment by jongfeel** [comment]
책이 좋다는 분이 또 등장했네요!

제가 곧 공지를 한번 올리고 책으로 변경할 수 있게 해보겠습니다.

어떤 책을 드려야 할지도 고민을 좀 해봐야 겠군요

**Comment by jongfeel** [comment]
업데이트가 늦었는데

온라인 개최로 인해 모든 참여자 분들에게 기념품을 드릴수가 없게 되었습니다.

다만 발표자 선물 및 kahoot it 게임 우승자에게는 선물을 드릴 예정입니다. (오프라인 직접 전달 혹은 배송)

내년 home coming day가 열리면 꼭 참여자 선물을 책으로 드릴 수 있도록 코로나 사태가 끝났으면 좋겠군요.
