### ISSUE TITLE
Pull request to presentation file

### ISSUE THREAD

**Issue by jongfeel** [ThinkAboutSoftware/HomeComingDay2020#17]
태원님 발표 자료만 없는 상태입니다.

시간 될 때 pull request로 추가해 주시면 좋을 것 같아요!

**Comment by ytw9699** [comment]
자료가 추가가 안되네요. Contributors가 안되서 그런걸까요?

**Comment by jongfeel** [comment]
fork를 하셔서 태원님 repsoitory에 추가하면 추가가 됩니다.
그 이후에 pull request를 해주시면 되요
