### ISSUE TITLE
kahoot it game winner is 4th place.

### ISSUE THREAD

**Issue by jongfeel** [ThinkAboutSoftware/HomeComingDay2020#4]
제가 ice breaking을 위해 kahoot it 게임을 준비했습니다.

온라인으로 스피드하게 문제를 맞추고 정답을 빨리 맞추는 순서에 따라 점수가 부여되서 매번 문제를 풀때 마다 등수를 체크할 수 있는 간단한 룰의 게임입니다.

youtube에 kahoot it 이라고 쳐 보시면 무슨 게임인지 쉽게 이해가 가실 겁니다.

지난 번 교육하는 사람들 밋업에서 프로그래머스에서 일하는 분이 제안해서 함께 해봤는데 상당히 재밌더라고요.
그리고 그 분이 이 게임을 많이 해보셨는지 몇 문제 풀다 보면 1등의 점수를 따라잡을 수 없게 되서 문제를 푸는 의지를 상실한다고 하더라고요.

그래서 게임을 너무 전투적으로 하지 말고 적당히 하라는 의미에서 4등을 하신 분에게 선물을 드릴 예정입니다.
대충 상위권에는 들어야 하지만 너무 문제를 빨리 잘 맞춰야하는 페이스를 조절해야 하고
그 타이밍에 하위권 사람들이 빨리 문제를 맞춰서 점수를 획득하고 적절한 순위 뒤집기의 긴장감을 조성할수 있게 될 겁니다.

---

이런 식의 제안과 같이 재밌고 즐거운 행사의 아이디어가 있으시면 얼른 issue에 글을 남겨주세요.

**Comment by fora22** [comment]
4위도 좋은 생각이지만 게임 중, 후반부터는 (총 인원 약 16명 기준)으로는 점수가 하위권 사람들도 힘들 것 같습니다. 
3위, 5위, 8위 정도로 후보자 3명을 뽑고 제비뽑기를 하는 것은 어떨까요? (너무 복잡스럽고 문제 열심히 푼 사람들에게 형평성 문제도 나올 것 같습니다만..ㅎ)

**Comment by jongfeel** [comment]
이렇게 하면 게임을 열심히 혹은 즐겁게 할 수 없기 때문에 보상이 1등에게 가는게 맞긴 합니다.

그런데 이 게임의 특성상 격차를 좁히기가 어려운 게임이기에 적당히 잘 해야 하면서도
너무 못따라오는 사람을 포기하게 만들지 않기 위한 장치로 4등을 선택한 것입니다.

예상하신 형평성 문제 때문에 너무 하위권 등수인 사람에게 보상이 가는 건 힘들 것 같습니다.
4등 정도면 충분히 하위권 사람들도 따라올 수 있을 것으로 봅니다.

**Comment by fora22** [comment]
넵 알겠습니다 ㅎㅎ

> 이렇게 하면 게임을 열심히 혹은 즐겁게 할 수 없기 때문에 보상이 1등에게 가는게 맞긴 합니다.
> 
> 그런데 이 게임의 특성상 격차를 좁히기가 어려운 게임이기에 적당히 잘 해야 하면서도
> 너무 못따라오는 사람을 포기하게 만들지 않기 위한 장치로 4등을 선택한 것입니다.
> 
> 예상하신 형평성 문제 때문에 너무 하위권 등수인 사람에게 보상이 가는 건 힘들 것 같습니다.
> 4등 정도면 충분히 하위권 사람들도 따라올 수 있을 것으로 봅니다.

**Comment by jongfeel** [comment]
Game winner is @ytw9699 

Prize is `Google Home Mini`
